#!/usr/bin/env python
import json, collections, re, os.path, subprocess

gitPattern = '([^/]+)/([^/]+)'
gitPattern = re.compile(gitPattern)
cleanComment = re.compile('^\s*//.*|^\s*$', re.MULTILINE)

def testGit(x):
    try:
        return gitPattern.findall(x)[0]
    except:
        return False

def gitAsyncClone(username, repo, path):
    url = 'https://github.com/%s/%s.git' % (username, repo)
    print url
    subprocess.Popen(['git', 'clone', '--depth', '1', url, path])

def installGit(username, repo):
    # url = 'https://github.com/%s/%s.git' % (username, repo)
    path = '~/.vim/cobalt/%s_%s' % (username, repo)
    path = os.path.expanduser(path)
    if os.path.exists(path):
        print "\033[90m%s\033[0m/\033[93m%s:\033[0m Already installed" % (username, repo)
        return
    gitAsyncClone(username, repo, path)
    print '%s/%s: Installing to %s' % (username, repo, path)

with open('plugins.json') as file:
    data = file.read()
    data = cleanComment.sub('', data)
    data = json.loads(data, object_pairs_hook=collections.OrderedDict)

    for plugin, options in data.items():
        # print
        match = testGit(plugin)
        if match:
            installGit(*match)
        else:
            print plugin, options
