iunmap <buffer>  <C-C>R
iunmap <buffer>  <C-C>L
iunmap <buffer>  <C-C>l
iunmap <buffer>  <C-C>c
iunmap <buffer>  <C-C>v
iunmap <buffer>  <C-C>p
iunmap <buffer>  <C-C>t
iunmap <buffer>  <C-C>s
iunmap <buffer>  <C-C>T
iunmap <buffer>  <C-C>o
iunmap <buffer>  <C-C>f
iunmap <buffer>  <C-C>k
iunmap <buffer>  <C-C>a
